import { WordCategory, Word, StoryTone } from './types';

export const MAX_WORDS_PER_ROUND = 5;

export const WORD_CATEGORY_THAI: Record<WordCategory, string> = {
  [WordCategory.ANIMALS_NATURE]: "สัตว์และธรรมชาติ",
  [WordCategory.FAMILY_PEOPLE]: "ครอบครัวและบุคคล",
  [WordCategory.FOOD_DRINK]: "อาหารและของกิน",
  [WordCategory.THINGS_TOYS]: "สิ่งของและของเล่น",
  [WordCategory.PLACES_ENVIRONMENT]: "สถานที่และสภาพแวดล้อม",
  [WordCategory.ACTIONS_EMOTIONS]: "กิริยาอาการและอารมณ์",
};

export const STORY_TONE_THAI: Record<StoryTone, string> = {
  [StoryTone.ADVENTURE]: "ผจญภัย",
  [StoryTone.HEARTWARMING]: "อบอุ่นและให้ข้อคิด",
  [StoryTone.FUNNY]: "สนุกสนานและเฮฮา",
  [StoryTone.DREAMY]: "ความฝันและจินตนาการ",
  [StoryTone.MYSTERY]: "สืบสวนและไขปริศนา",
  [StoryTone.RELATIONSHIPS]: "ความสัมพันธ์และมิตรภาพ",
};

export const STORY_FOLLOW_UP_QUESTIONS_TH: string[] = [
  "แล้วจะเกิดอะไรขึ้นต่อไปนะ?",
  "เล่าให้ฟังหน่อยสิ ว่าเรื่องราวจะเป็นยังไงต่อ",
  "ตาของน้องๆ แล้ว ลองแต่งเรื่องต่อจากนี้ดูสิ",
  "น้องๆ อยากให้พวกเขาทำอะไรกันต่อดี?",
  "แล้วเหตุการณ์ต่อไปจะเป็นยังไงนะ?",
  "ช่วยคิดหน่อยสิ ว่าจะเกิดอะไรขึ้นต่อไป",
  "มีไอเดียอะไรเจ๋งๆ สำหรับฉากต่อไปไหม?",
  "แล้วการผจญภัยของพวกเขาจะเป็นอย่างไรต่อไป?",
  "น้องๆ คิดว่าพวกเขาควรจะไปที่ไหนต่อ?",
  "จะเกิดเรื่องน่าตื่นเต้นอะไรขึ้นอีกนะ?",
  "บอกหน่อยสิ ว่าเรื่องราวจะดำเนินต่อไปอย่างไร",
  "แล้วพวกเขาจะเจอกับอะไรต่อไป?",
  "อยากให้เกิดอะไรขึ้นในฉากต่อไป เล่ามาได้เลย",
  "น้องๆ ลองจินตนาการดูสิ ว่าจะเกิดอะไรขึ้น",
  "มาช่วยกันแต่งเรื่องต่อให้จบกันเถอะ!",
  "แล้วพวกเขาก็... (ให้น้องๆ เติม)",
  "น้องๆ คิดว่าใครจะโผล่มาในฉากต่อไป?",
  "เรื่องราวต่อไปขึ้นอยู่กับน้องๆ แล้วนะ",
  "แล้วทางไหนคือทางที่พวกเขาจะเลือกไปต่อ?",
  "มีอะไรสนุกๆ รอพวกเขาอยู่ข้างหน้านะ?",
  "เล่าตอนต่อไปให้ฟังหน่อยได้ไหม?",
  "จะเกิดอะไรขึ้นกับเพื่อนๆ ของเราต่อไปนะ?",
  "น้องๆ อยากเห็นอะไรในฉากต่อไป?",
  "แล้วพวกเขาจะแก้ปัญหานี้ยังไงดี?",
  "มาดูกันสิว่าน้องๆ จะแต่งเรื่องได้เก่งแค่ไหน",
  "แล้วตัวละครใหม่จะโผล่มาไหมนะ?",
  "ต่อไปจะเป็นฉากที่น่าตื่นเต้นที่สุดเลย! น้องๆ คิดว่าคืออะไร?",
  "แล้วแผนการต่อไปของพวกเขาคืออะไร?",
  "น้องๆ คือผู้กำกับเรื่องนี้นะ สั่งมาได้เลย!",
  "เรื่องราวจะเป็นยังไงต่อนะ บอกไอเดียของน้องๆ มาได้เลย",
];

export const STORY_FOLLOW_UP_QUESTIONS_EN: string[] = [
  "So, what do you think should happen next?",
  "And what happens next? What do you think?",
  "How does the story continue? Tell me your ideas!",
  "What should they do next?",
  "Now it's your turn. What happens in the next part of the story?",
  "What happens after that?",
  "Tell me what happens in the next scene.",
  "It's up to you now! What's next?",
  "What adventure is waiting for them?",
  "What exciting thing will happen now?",
  "Where should they go from here?",
  "Who do you think they will meet next?",
  "Use your imagination! What comes next?",
  "Let's continue the story together. What's your idea?",
  "And then... (you can fill in the blank)",
  "What's their next move?",
  "What happens to our friends now?",
  "What do you want to see in the next scene?",
  "How will they solve this problem?",
  "I can't wait to hear what you come up with!",
  "The next part of the story is all yours.",
  "What choice will they make now?",
  "What fun is waiting for them around the corner?",
  "Can you tell me the next part?",
  "What's going to happen to our heroes?",
  "You're the storyteller now. Go ahead!",
  "What's their next plan?",
  "What mystery will they uncover next?",
  "Tell me, what should happen right now?",
  "Let's see what amazing idea you have!",
];

export const VOCABULARY: Record<WordCategory, Word[]> = {
  [WordCategory.ANIMALS_NATURE]: [
    { thai: "สุนัข", english: "dog" }, { thai: "แมว", english: "cat" }, { thai: "ต้นไม้", english: "tree" }, { thai: "ดอกไม้", english: "flower" }, { thai: "สิงโต", english: "lion" },
    { thai: "เสือ", english: "tiger" }, { thai: "ช้าง", english: "elephant" }, { thai: "ลิง", english: "monkey" }, { thai: "งู", english: "snake" }, { thai: "นก", english: "bird" },
    { thai: "ปลา", english: "fish" }, { thai: "แม่น้ำ", english: "river" }, { thai: "ภูเขา", english: "mountain" }, { thai: "พระอาทิตย์", english: "sun" }, { thai: "พระจันทร์", english: "moon" },
    { thai: "ดาว", english: "star" }, { thai: "เมฆ", english: "cloud" }, { thai: "ฝน", english: "rain" }, { thai: "ลม", english: "wind" }, { thai: "ใบไม้", english: "leaf" },
    { thai: "หญ้า", english: "grass" }, { thai: "ทราย", english: "sand" }, { thai: "หิน", english: "stone" }, { thai: "หมี", english: "bear" }, { thai: "ยีราฟ", english: "giraffe" },
    { thai: "ม้าลาย", english: "zebra" }, { thai: "หมาป่า", english: "wolf" }, { thai: "สุนัขจิ้งจอก", english: "fox" }, { thai: "กระต่าย", english: "rabbit" }, { thai: "กวาง", english: "deer" },
    { thai: "กระรอก", english: "squirrel" }, { thai: "ผึ้ง", english: "bee" }, { thai: "ผีเสื้อ", english: "butterfly" }, { thai: "มด", english: "ant" }, { thai: "แมงมุม", english: "spider" },
    { thai: "กบ", english: "frog" }, { thai: "เต่า", english: "turtle" }, { thai: "จระเข้", english: "crocodile" }, { thai: "ปลาวาฬ", english: "whale" }, { thai: "ปลาโลมา", english: "dolphin" },
    { thai: "ฉลาม", english: "shark" }, { thai: "ปลาหมึก", english: "octopus" }, { thai: "ปู", english: "crab" }, { thai: "กุ้ง", english: "shrimp" }, { thai: "นกอินทรี", english: "eagle" },
    { thai: "นกฮูก", english: "owl" }, { thai: "เพนกวิน", english: "penguin" }, { thai: "จิงโจ้", english: "kangaroo" }, { thai: "โคอาล่า", english: "koala" }, { thai: "หอยทาก", english: "snail" }
  ],
  [WordCategory.FAMILY_PEOPLE]: [
    { thai: "แม่", english: "mother" }, { thai: "พ่อ", english: "father" }, { thai: "ทารก", english: "baby" }, { thai: "เพื่อน", english: "friend" }, { thai: "ครู", english: "teacher" },
    { thai: "ย่า", english: "grandmother" }, { thai: "ปู่", english: "grandfather" }, { thai: "พี่ชาย", english: "brother" }, { thai: "พี่สาว", english: "sister" }, { thai: "ป้า", english: "aunt" },
    { thai: "ลุง", english: "uncle" }, { thai: "ลูกพี่ลูกน้อง", english: "cousin" }, { thai: "หมอ", english: "doctor" }, { thai: "พยาบาล", english: "nurse" }, { thai: "ตำรวจ", english: "police officer" },
    { thai: "นักดับเพลิง", english: "firefighter" }, { thai: "ชาวนา", english: "farmer" }, { thai: "นักเรียน", english: "student" }, { thai: "ศิลปิน", english: "artist" }, { thai: "นักร้อง", english: "singer" },
    { thai: "นักเต้น", english: "dancer" }, { thai: "นักเขียน", english: "writer" }, { thai: "นักแสดง", english: "actor" }, { thai: "นักบิน", english: "pilot" }, { thai: "เชฟ", english: "chef" },
    { thai: "ทหาร", english: "soldier" }, { thai: "นักกีฬา", english: "athlete" }, { thai: "นักวิทยาศาสตร์", english: "scientist" }, { thai: "วิศวกร", english: "engineer" }, { thai: "ทันตแพทย์", english: "dentist" },
    { thai: "ทนาย", english: "lawyer" }, { thai: "ผู้พิพากษา", english: "judge" }, { thai: "คนขับรถ", english: "driver" }, { thai: "แคชเชียร์", english: "cashier" }, { thai: "ผู้จัดการ", english: "manager" },
    { thai: "ประธานาธิบดี", english: "president" }, { thai: "ราชา", english: "king" }, { thai: "ราชินี", english: "queen" }, { thai: "เจ้าชาย", english: "prince" }, { thai: "เจ้าหญิง", english: "princess" },
    { thai: "เด็กชาย", english: "boy" }, { thai: "เด็กหญิง", english: "girl" }, { thai: "ผู้ชาย", english: "man" }, { thai: "ผู้หญิง", english: "woman" }, { thai: "ยักษ์", english: "giant" }
  ],
  [WordCategory.FOOD_DRINK]: [
    { thai: "แอปเปิ้ล", english: "apple" }, { thai: "นม", english: "milk" }, { thai: "ขนมปัง", english: "bread" }, { thai: "น้ำ", english: "water" }, { thai: "เค้ก", english: "cake" },
    { thai: "ข้าว", english: "rice" }, { thai: "ก๋วยเตี๋ยว", english: "noodle" }, { thai: "ซุป", english: "soup" }, { thai: "สลัด", english: "salad" }, { thai: "พิซซ่า", english: "pizza" },
    { thai: "แฮมเบอร์เกอร์", english: "hamburger" }, { thai: "แซนด์วิช", english: "sandwich" }, { thai: "ไส้กรอก", english: "sausage" }, { thai: "ชีส", english: "cheese" }, { thai: "เนย", english: "butter" },
    { thai: "ไข่", english: "egg" }, { thai: "น้ำตาล", english: "sugar" }, { thai: "เกลือ", english: "salt" }, { thai: "พริกไทย", english: "pepper" }, { thai: "น้ำผลไม้", english: "juice" },
    { thai: "กาแฟ", english: "coffee" }, { thai: "ชา", english: "tea" }, { thai: "ช็อคโกแลต", english: "chocolate" }, { thai: "ไอศกรีม", english: "ice cream" }, { thai: "คุกกี้", english: "cookie" },
    { thai: "ลูกอม", english: "candy" }, { thai: "ผลไม้", english: "fruit" }, { thai: "ผัก", english: "vegetable" }, { thai: "เนื้อ", english: "meat" }, { thai: "ปลา", english: "fish" },
    { thai: "ไก่", english: "chicken" }, { thai: "เนื้อวัว", english: "beef" }, { thai: "เนื้อหมู", english: "pork" }, { thai: "มันฝรั่ง", english: "potato" }, { thai: "มะเขือเทศ", english: "tomato" },
    { thai: "หัวหอม", english: "onion" }, { thai: "กระเทียม", english: "garlic" }, { thai: "แครอท", english: "carrot" }, { thai: "บรอกโคลี", english: "broccoli" }, { thai: "กะหล่ำปลี", english: "cabbage" },
    { thai: "ข้าวโพด", english: "corn" }, { thai: "แตงกวา", english: "cucumber" }, { thai: "มะนาว", english: "lemon" }, { thai: "ส้ม", english: "orange" }, { thai: "องุ่น", english: "grape" },
    { thai: "กล้วย", english: "banana" }, { thai: "สตรอเบอร์รี่", english: "strawberry" }, { thai: "แตงโม", english: "watermelon" }, { thai: "สับปะรด", english: "pineapple" }, { thai: "โดนัท", english: "donut" }
  ],
  [WordCategory.THINGS_TOYS]: [
    { thai: "หนังสือ", english: "book" }, { thai: "ลูกบอล", english: "ball" }, { thai: "บ้าน", english: "house" }, { thai: "เก้าอี้", english: "chair" }, { thai: "รถยนต์", english: "car" },
    { thai: "โต๊ะ", english: "table" }, { thai: "เตียง", english: "bed" }, { thai: "ประตู", english: "door" }, { thai: "หน้าต่าง", english: "window" }, { thai: "โคมไฟ", english: "lamp" },
    { thai: "นาฬิกา", english: "clock" }, { thai: "โทรศัพท์", english: "phone" }, { thai: "คอมพิวเตอร์", english: "computer" }, { thai: "โทรทัศน์", english: "television" }, { thai: "กล้อง", english: "camera" },
    { thai: "ปากกา", english: "pen" }, { thai: "ดินสอ", english: "pencil" }, { thai: "กระดาษ", english: "paper" }, { thai: "กรรไกร", english: "scissors" }, { thai: "กาว", english: "glue" },
    { thai: "ไม้บรรทัด", english: "ruler" }, { thai: "ยางลบ", english: "eraser" }, { thai: "กระเป๋า", english: "bag" }, { thai: "กล่อง", english: "box" }, { thai: "กุญแจ", english: "key" },
    { thai: "ถ้วย", english: "cup" }, { thai: "จาน", english: "plate" }, { thai: "ช้อน", english: "spoon" }, { thai: "ส้อม", english: "fork" }, { thai: "มีด", english: "knife" },
    { thai: "ตุ๊กตา", english: "doll" }, { thai: "ตุ๊กตาหมี", english: "teddy bear" }, { thai: "หุ่นยนต์", english: "robot" }, { thai: "ตัวต่อ", english: "puzzle" }, { thai: "ว่าว", english: "kite" },
    { thai: "กลอง", english: "drum" }, { thai: "กีตาร์", english: "guitar" }, { thai: "เปียโน", english: "piano" }, { thai: "จักรยาน", english: "bicycle" }, { thai: "สเก็ตบอร์ด", english: "skateboard" },
    { thai: "สกู๊ตเตอร์", english: "scooter" }, { thai: "รถไฟ", english: "train" }, { thai: "เครื่องบิน", english: "plane" }, { thai: "เรือ", english: "boat" }, { thai: "ลูกโป่ง", english: "balloon" }
  ],
  [WordCategory.PLACES_ENVIRONMENT]: [
    { thai: "โรงเรียน", english: "school" }, { thai: "สวน", english: "park" }, { thai: "ทะเล", english: "sea" }, { thai: "ภูเขา", english: "mountain" }, { thai: "เมือง", english: "city" },
    { thai: "บ้าน", english: "home" }, { thai: "ออฟฟิศ", english: "office" }, { thai: "ห้องสมุด", english: "library" }, { thai: "พิพิธภัณฑ์", english: "museum" }, { thai: "โรงพยาบาล", english: "hospital" },
    { thai: "สนามบิน", english: "airport" }, { thai: "สถานี", english: "station" }, { thai: "ธนาคาร", english: "bank" }, { thai: "ไปรษณีย์", english: "post office" }, { thai: "ตลาด", english: "market" },
    { thai: "ซูเปอร์มาร์เก็ต", english: "supermarket" }, { thai: "ร้านอาหาร", english: "restaurant" }, { thai: "คาเฟ่", english: "cafe" }, { thai: "โรงภาพยนตร์", english: "cinema" }, { thai: "โรงละคร", english: "theater" },
    { thai: "สนามกีฬา", english: "stadium" }, { thai: "สนามเด็กเล่น", english: "playground" }, { thai: "สวนสัตว์", english: "zoo" }, { thai: "ชายหาด", english: "beach" }, { thai: "ป่า", english: "forest" },
    { thai: "ทะเลทราย", english: "desert" }, { thai: "เกาะ", english: "island" }, { thai: "ประเทศ", english: "country" }, { thai: "ทวีป", english: "continent" }, { thai: "ดาวเคราะห์", english: "planet" },
    { thai: "อวกาศ", english: "space" }, { thai: "ท้องฟ้า", english: "sky" }, { thai: "พื้นดิน", english: "ground" }, { thai: "ถนน", english: "road" }, { thai: "ถนน", english: "street" },
    { thai: "สะพาน", english: "bridge" }, { thai: "ตึก", english: "building" }, { thai: "หอคอย", english: "tower" }, { thai: "ปราสาท", english: "castle" }, { thai: "วัด", english: "temple" },
    { thai: "ฟาร์ม", english: "farm" }, { thai: "ห้องเรียน", english: "classroom" }, { thai: "ห้องนอน", english: "bedroom" }, { thai: "ห้องครัว", english: "kitchen" }, { thai: "ห้องน้ำ", english: "bathroom" }
  ],
  [WordCategory.ACTIONS_EMOTIONS]: [
    { thai: "วิ่ง", english: "run" }, { thai: "กิน", english: "eat" }, { thai: "นอน", english: "sleep" }, { thai: "มีความสุข", english: "happy" }, { thai: "เศร้า", english: "sad" },
    { thai: "เดิน", english: "walk" }, { thai: "กระโดด", english: "jump" }, { thai: "ว่ายน้ำ", english: "swim" }, { thai: "บิน", english: "fly" }, { thai: "เต้น", english: "dance" },
    { thai: "ร้องเพลง", english: "sing" }, { thai: "อ่าน", english: "read" }, { thai: "เขียน", english: "write" }, { thai: "วาดรูป", english: "draw" }, { thai: "เล่น", english: "play" },
    { thai: "ทำงาน", english: "work" }, { thai: "เรียน", english: "study" }, { thai: "คิด", english: "think" }, { thai: "พูด", english: "talk" }, { thai: "ฟัง", english: "listen" },
    { thai: "มอง", english: "look" }, { thai: "เห็น", english: "see" }, { thai: "สัมผัส", english: "touch" }, { thai: "รู้สึก", english: "feel" }, { thai: "ดมกลิ่น", english: "smell" },
    { thai: "ชิมรส", english: "taste" }, { thai: "หัวเราะ", english: "laugh" }, { thai: "ร้องไห้", english: "cry" }, { thai: "ยิ้ม", english: "smile" }, { thai: "โกรธ", english: "angry" },
    { thai: "หิว", english: "hungry" }, { thai: "กระหายน้ำ", english: "thirsty" }, { thai: "เหนื่อย", english: "tired" }, { thai: "ง่วงนอน", english: "sleepy" }, { thai: "ประหลาดใจ", english: "surprised" },
    { thai: "กลัว", english: "scared" }, { thai: "เบื่อ", english: "bored" }, { thai: "ตื่นเต้น", english: "excited" }, { thai: "ภูมิใจ", english: "proud" }, { thai: "อาย", english: "shy" },
    { thai: "กังวล", english: "worried" }, { thai: "สับสน", english: "confused" }, { thai: "สงบ", english: "calm" }, { thai: "กล้าหาญ", english: "brave" }, { thai: "ใจดี", english: "kind" }
  ],
};